{% set name = "responses" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 644905bc4fb8a18fa37e3882b2ac05e610fe8c2f967d327eed669e314d94a541

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python
    - pip
    - pytest
  run:
    - python
    - requests >=2.0
    - urllib3 >=1.25.10
    - six

test:
  imports:
    - responses

about:
  home: https://github.com/getsentry/responses
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A utility library for mocking out the `requests` Python library.

extra:
  recipe-maintainers:
    - mariusvniekerk
