{% set name = "responses" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17dcd2facb12182ec353b05b424b2e3f52783f0bf3ad6586e098a11ba75fa666

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - cookies
    - python
    - requests >=2.0
    - six

test:
  imports:
    - responses

about:
  home: https://github.com/getsentry/responses
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A utility library for mocking out the `requests` Python library.

extra:
  recipe-maintainers:
    - mariusvniekerk
